// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyIUovXbbtdewCmGsGcPI6CX___SF9mfw',
    appId: '1:243854528757:web:4fb298d84e656918c935bc',
    messagingSenderId: '243854528757',
    projectId: 'user-management-8dcde',
    authDomain: 'user-management-8dcde.firebaseapp.com',
    storageBucket: 'user-management-8dcde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvv3cfvL1SI6j2yuuCcZQUtiwssHTBmnE',
    appId: '1:243854528757:android:e817c6e8ef2923ccc935bc',
    messagingSenderId: '243854528757',
    projectId: 'user-management-8dcde',
    storageBucket: 'user-management-8dcde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1fPcakyartWz1bfhR3c9_4-9U8YCx-J0',
    appId: '1:243854528757:ios:da640f20cea40367c935bc',
    messagingSenderId: '243854528757',
    projectId: 'user-management-8dcde',
    storageBucket: 'user-management-8dcde.appspot.com',
    iosBundleId: 'com.example.userManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1fPcakyartWz1bfhR3c9_4-9U8YCx-J0',
    appId: '1:243854528757:ios:d2568cc3e860402ac935bc',
    messagingSenderId: '243854528757',
    projectId: 'user-management-8dcde',
    storageBucket: 'user-management-8dcde.appspot.com',
    iosBundleId: 'com.example.userManagement.RunnerTests',
  );
}
